<a href="https://colab.research.google.com/github/empLittlewhite/Go-Learning/blob/master/%E6%95%B0%E6%8D%AE%E5%A4%84%E7%90%86.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [63]:
import torch
import numpy as np
import os
import pandas as pd

In [41]:
x = torch.arange(12)
x
x.shape
x.numel()

12

In [42]:
x.shape
# number of elements
x.numel

<function Tensor.numel>

In [43]:
torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])
torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]]).shape

torch.Size([3, 4])

In [44]:
x = torch.tensor([1.0,2,4,8])
y = torch.tensor([2,2,2,2])
# **是求幂次
x+y,x-y,x*y,x/y,x**y,

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [45]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [46]:
x = torch.arange(12,dtype=torch.float32).reshape((3,4))
y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
torch.cat((x,y),dim=0),torch.cat((x,y),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [47]:
x == y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [48]:
# 对所有元素进行求和
x.sum()

tensor(66.)

In [49]:
# 数组的形状不同，广播机制
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a,b


(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [50]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [51]:
x[-1],x[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [52]:
x[1,2] = 9
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [53]:
#  id是唯一变量标识，类似cpp种的地址
# python中可能会出现内存分配的情况，当数组很大，数组复制的时候
before = id(y)
y = y+x
id(y) == before

False

In [54]:
# 执行原地操作，避免新结果分配内存
# z的数据类型和y是一样的，但是元素都是0 zeros_like
z = torch.zeros_like(y)
print("id(z):",id(z))
z[:] = x+y
print("id(z):",id(z))


id(z): 137944967865072
id(z): 137944967865072


In [55]:
#或者之后不使用之前的X，直接
before = id(x)
x += y
id(x) == before

True

In [59]:
# numpy  和  torch  的张量
A = x.numpy()
B = torch.tensor(A)
type(A),type(B)


(numpy.ndarray, torch.Tensor)

In [60]:
# 将tensor转变成标量（一维）
a = torch.tensor([3.5])
a,a.item(),float(a),int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

In [62]:
os.makedirs(os.path.join('..','data'),exist_ok= True)
data_file = os.path.join('..','data','house_tiny.csv')
with open(data_file,'w') as f:
  f.write('NumRooms,Alley,Price\n')#列名
  f.write('NA,Pave,127500\n')
  f.write('2,NA,106000\n')#每一行表示一个数据样本
  f.write('4,NA,178100\n')
  f.write('NA,NA,140000\n')

In [65]:
# 如果没有pandas
# !pip install pandas
data = pd.read_csv(data_file)
print(data)
data

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

In [72]:
#处理缺失数据
# iloc   index location
# iloc[:,0:2]第一、二列的所有行
inputs, outputs = data.iloc[:,0:2],data.iloc[:,2]
# fill填充 not a number   填充值是均值
inputs = inputs.fillna(inputs.mean(numeric_only=1))
print(inputs)


   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


In [75]:
# inputs中的值是离散的，可以将NaN视作一个类别
# 类似one-hot的编码形式
inputs = pd.get_dummies(inputs,dummy_na=1)
print(inputs)



   NumRooms  Alley_Pave  Alley_nan
0       3.0        True      False
1       2.0       False       True
2       4.0       False       True
3       3.0       False       True


In [78]:
# 将表格的内容转变成tensor
x,y = torch.tensor(inputs.values.astype(np.float32)),torch.tensor(outputs.values.astype(np.float32))
x,y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]]),
 tensor([127500., 106000., 178100., 140000.]))